# Generated by Django 4.2.18 on 2026-09-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentembedding',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
